[build]
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "/plugins/netlify-plugin-stepzen"

[template]
  incoming-hooks = ["StepZen"]

[template.environment]
  STEPZEN_ACCOUNT = "Add your StepZen account name"
  STEPZEN_ADMIN_KEY = "Add your StepZen admin key"
  STEPZEN_FOLDER = "Name your folder. Defaults to netlify"
  STEPZEN_NAME = "Name your endpoint. Defaults to endpoint"
